addSbtPlugin("com.geirsson"       % "sbt-scalafmt" % "0.4.10")
addSbtPlugin("com.typesafe.sbt"   % "sbt-git"      % "0.8.5")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"   % "1.6.0")
addSbtPlugin("io.get-coursier"    % "sbt-coursier" % "1.0.0-M14")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"      % "0.2.17")
